server:
  port: 11938

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/bens?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: root
          password: abc123456
        tdengine:
          url: jdbc:TAOS-RS://129.28.26.35:50006/bens
          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
          username: root
          password: TMPKaPTMt3G5z5cC
          druid:
            validation-query: SELECT SERVER_STATUS() # TDengine 数据源的有效性检查 SQL
  redis:
    host: 127.0.0.1
    port: 6379
    database: 6
    # password: